name: CI Combined Build (Frontend & API)

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-24.04
    timeout-minutes: 1

    outputs:
      frontend-docker-tags: ${{ steps.generate_frontend_tags.outputs.docker_tags }}
      api-docker-tags: ${{ steps.generate_api_tags.outputs.docker_tags }}

    steps:
      - id: generate_frontend_tags
        run: |
          docker_registry_path="ghcr.io/edulution-io/edulution-ui"
          docker_tags="$docker_registry_path:$(echo ${{ github.ref }} | cut -d'/' -f3- | sed 's/[^a-z0-9_-]/-/gi')"
          if [[ ${{ github.ref }} = 'refs/heads/master' ]] || [[ ${{ github.ref }} =~ ^refs/tags/v.*$ ]]
          then
            docker_tags+=",$docker_registry_path:latest"
          fi
          echo "docker_tags=$docker_tags" >> $GITHUB_OUTPUT

      - id: generate_api_tags
        run: |
          docker_registry_path="ghcr.io/edulution-io/edulution-api"
          docker_tags="$docker_registry_path:$(echo ${{ github.ref }} | cut -d'/' -f3- | sed 's/[^a-z0-9_-]/-/gi')"
          if [[ ${{ github.ref }} = 'refs/heads/master' ]] || [[ ${{ github.ref }} =~ ^refs/tags/v.*$ ]]
          then
            docker_tags+=",$docker_registry_path:latest"
          fi
          echo "docker_tags=$docker_tags" >> $GITHUB_OUTPUT

  build-frontend:
    runs-on: ubuntu-24.04
    needs: prepare
    timeout-minutes: 10

    steps:
      - run: echo Use docker tags ${{ needs.prepare.outputs.frontend-docker-tags }}

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ github.token }}

      - name: Use Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22.x

      - name: Cache Node.js modules
        uses: actions/cache@v4.2.0
        continue-on-error: true
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Frontend
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6.10.0
        with:
          build-args: |
            buildId=${{ github.sha }}
            version=${{ needs.prepare.outputs.frontend-docker-tags }}
          context: .
          file: apps/frontend/Dockerfile
          push: true
          tags: ${{ needs.prepare.outputs.frontend-docker-tags }}

  build-api:
    runs-on: ubuntu-24.04
    needs: prepare
    timeout-minutes: 10

    steps:
      - run: echo Use docker tags ${{ needs.prepare.outputs.api-docker-tags }}

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ github.token }}

      - name: Use Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22.x

      - name: Cache Node.js modules
        uses: actions/cache@v4.2.0
        continue-on-error: true
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Backend
        run: npm run build:api

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6.10.0
        with:
          build-args: |
            buildId=${{ github.sha }}
            version=${{ needs.prepare.outputs.api-docker-tags }}
          context: .
          file: apps/api/Dockerfile
          push: true
          tags: ${{ needs.prepare.outputs.api-docker-tags }}
